# Generated by Django 5.1.2 on 2024-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='hj', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.TextField(default=112),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phn',
            field=models.IntegerField(default='yjhj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=544376),
            preserve_default=False,
        ),
    ]
